GET http://localhost:3000

### Show All Students

GET http://localhost:3000/students

### Show Student

GET http://localhost:3000/students/2

### Create Student

POST http://localhost:3000/students
Content-Type: application/json

{
    "name": "Blind Adam",
    "gender": "m",
    "course_id": 1
}

### Update Student

PUT http://localhost:3000/students/3
Content-Type: application/json

{
    "name": "Zaki Ahmed",
    "gender": "m",
    "course_id": 2
}

### Partial Update Student (course_id)

PATCH http://localhost:3000/students/3
Content-Type: application/json

{
    "course_id": 3
}

### Delete Student
DELETE http://localhost:3000/students/3